### ISSUE TITLE
[Bug] Manual user "can_download" get's overwritten by AutoGroup system

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1820]
**Describe the bug**
When setting the download permission of a user, it's gets overwritten in certain intervals by the AutoGroup system.

**To Reproduce**
1. Set "can_download" from a user
2. Wait for AutoGroup / or some other system
3. See the user getting the can_download permission back

**Expected behavior**
AutoGroup System should respect the pemission set to a specific user.

**Screenshots**
n/a

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: Ver. 8.43.0
- PHP Version: php8.0.7
- Database Driver & Version: 8.0.25-0ubuntu0.20.04.1
- Web Server Driver & Version: ubuntu 20.04
- OS Driver and Version: ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**
I am not entirely sure if it is the AutoGroup System, but this is the most likely culprit.

**Possible Fix?**
n/a

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/1820">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/1820/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/1820/pledge.svg">
</picture>
</a>

**Comment by Alkl58** [comment]
Issue seems to be: 
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/f801b148dbc316a01ee7444f12e43c100f002205/app/Console/Commands/AutoRevokePermissions.php#L56

In my opinion this line is not needed, as `'can_download' => '1'` should be set by autogroup.

**Comment by Audionut** [comment]
This seems fixed now.

**Comment by Roardom** [comment]
This is not fixed: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/e736d2973fd6d2af5f219832475735fd81b1b37c/app/Console/Commands/AutoGroup.php#L82

**Comment by Roardom** [comment]
Related: #4428
